#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd


# In[2]:


df1 = pd.read_excel("JS-data.xlsx")


# In[3]:


len(df1)


# In[4]:


len(df1.columns)


# In[5]:


empty_columns = ["SHIFT","DISCOFFERID","SECTION","SHELF","STATEMENTCODE","DISCGROUPID","ITEMPOSTINGGROUP","VARIANTID","PERIODICDISCGROUP"
                 ,"PURCHID","FILELOGID","CONCESSIONCONTRACTID","CONCESSIONSETTLEMENTID","CONSESSIONPARTPAYMENTID","PRESCRIPTIONID",
                 "COMMENT_","INVENTBATCHID","RFIDTAGID","INVENTSERIALID","RETURNTRANSACTIONID","TAXITEMGROUP","ORIGINALTAXITEMGROUP",
                 "DLVMODE","ELECTRONICDELIVERYEMAIL","ELECTRONICDELIVERYEMAILCONTENT","INVENTLOCATIONID","LISTINGID",
                "ORIGIN","RETURNSTORE","RETURNTERMINALID","CUSTACCOUNTASYNC","HSNCODE_IN","SERVICEACCOUNTINGCODE_IN","STAFFID"    
                 ,"ORIGINALTAXGROUP","INVENTSITEID","MODIFIEDBY","CREATEDBY","DATAAREAID","EXEMPT_IN","GIFTCARDBALANCE",
                 "DEL_CREATEDTIME","DEL_MODIFIEDTIME","SKIPSALESLINE_RU","LINEMANUALDISCOUNTPERCENTAGE","LOGISTICSPOSTALADDRESS"
                 ,"LINEMANUALDISCOUNTAMOUNT","CATALOG","BLOCKQTY","GIFTCARD","PUMPID","INVENTDIMID","PERIODICDISCTYPE",
                 "TOTALDISCINFOCODELINENUM","CUSTINVOICEDISCAMOUNT","INFOCODEDISCAMOUNT","CUSTDISCAMOUNT","REPLICATED"
                 ,"LINEDSCAMOUNT","TOTALROUNDEDAMOUNT","ORIGINALOFLINKEDITEMLIST","LINKEDITEMNOTORIGINAL","ITEMCORRECTEDLINE","WEIGHTITEM",
                 "SCALEITEM","WEIGHTMANUALLYENTERED","PRICEINBARCODE","TRANSACTIONCODE","CURRENCY","NETPRICE","STDNETPRICE"
                 ,"DISCAMOUNTFROMSTDPRICE"
                
]


# In[6]:


len(empty_columns)


# In[7]:


df1 = df1.drop(empty_columns, axis=1)


# In[8]:


len(df1.columns)


# In[9]:


sum(df1.apply(lambda x: sum(x.isnull().values), axis = 1)>0)


# In[10]:


len(df1)


# In[12]:


df1.head()


# In[13]:


df1.dropna(inplace=True)


# In[14]:


len(df1)


# In[15]:


df1.to_csv("RETAILTRANSACTIONSALESTRANS.csv")

